package domain.map;

import domain.map.tiles.BasicDelimiter;
import domain.map.tiles.BigSnowHeap;
import domain.map.tiles.Ice;
import domain.map.tiles.SmallSnowHeap;
import domain.map.tiles.Snow;
import domain.map.tiles.Tile;
import domain.map.tiles.TileBehaviors;
import domain.map.tiles.TileId;
import exceptions.SharedException;

public class TileFactory {
	public static Tile get (final char id) throws SharedException {
		switch (id) {
			case TileId.DELIMITER_BASIC: return new BasicDelimiter();
			case TileId.BLOCK_ICE: return new Ice();
			case TileId.FLOOR_BIG_SNOW_HEAP: return new BigSnowHeap();
			case TileId.FLOOR_SMALL_SNOW_HEAP: return new SmallSnowHeap();
			case TileId.EMPTY: return new Snow();
		}
		
		// NO OTHER ID SHOULD BE GENERATED BY THE FACTORY
		throw new SharedException(SharedException.invalidTileId(id));
	}
}
